# fly.toml app configuration file generated for email-templates-resend-api on 2026-07-06T20:54:09Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'email-templates-resend-api'
primary_region = 'yyz'

[build]

[deploy]
  release_command = 'bunx prisma migrate deploy'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 512

[[vm]]
  memory = '2gb'
  cpu_kind = 'performance'
  cpus = 1
  memory_mb = 2048
  processes = ['app']
  size = 'performance-cpu-1x'
