# fly.toml app configuration file generated for email-templates-resend-api on 2026-05-21T17:29:02-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'email-templates-resend-api'
primary_region = 'yyz'

[build]

[deploy]
  release_command = 'bunx prisma migrate deploy'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpus = 1
  memory_mb = 1024
