# fly.toml app configuration file generated for email-templates-resend-api on 2026-05-22T17:12:17-04:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'email-templates-resend-api'
primary_region = 'yyz'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = true
  min_machines_running = 1

  [http_service.concurrency]
    type = 'requests'
    hard_limit = 100
    soft_limit = 50

  [[http_service.checks]]
    interval = '15s'
    timeout = '2s'
    grace_period = '5s'
    method = 'GET'
    path = '/health'

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpus = 1
  memory_mb = 256
